### ISSUE TITLE
TTGO T-Display no longer works onnew upload

### ISSUE THREAD

**Issue by schuh8** [Xinyuan-LilyGO/TTGO-T-Display#105]
I have an internet radio based on the TTGO T-display and a DAC board uploaded with Arduino IDK. It has worked flawlessly for many months and I have occasionally added new streaming stations and reuploaded the code. This morning I modified the code to add a new station. On uploading the radio works fine (new station and all) but I have no display at all. The screen has that grayish look so I know it's on but no characters display. 

Can this be due a version of a library having been updated? Any help/suggestions greatly appreciated!

These are the libraries:

#include "Arduino.h"
#include "WiFi.h"
#include "Audio.h"
#include "time.h"
#include <TFT_eSPI.h>

**Comment by teastainGit** [comment]
Sudden LilyGO display issues are often related to what version of the library you are using.

You MUST use the library supplied by LilyGO in the GitHub repository, because there is a setup file that chooses your resolution and SPI, vs i8080 parallel, plus frequency.

What version are you now running?

**Comment by schuh8** [comment]
That worked ... Thank You
